/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type * as aggregateStats from "../aggregateStats.js";
import type * as audienceInsights from "../audienceInsights.js";
import type * as audit from "../audit.js";
import type * as auth_discord from "../auth_discord.js";
import type * as auth_helpers from "../auth_helpers.js";
import type * as backfillMatchStats from "../backfillMatchStats.js";
import type * as bandwidthBackfill from "../bandwidthBackfill.js";
import type * as cacheStatus from "../cacheStatus.js";
import type * as calculateContributionScore from "../calculateContributionScore.js";
import type * as cleanup from "../cleanup.js";
import type * as cleanupDuplicates from "../cleanupDuplicates.js";
import type * as clearDeprecatedPlayerRankingFields from "../clearDeprecatedPlayerRankingFields.js";
import type * as clearDeprecatedTierEvalPrFields from "../clearDeprecatedTierEvalPrFields.js";
import type * as crons from "../crons.js";
import type * as dataBackup from "../dataBackup.js";
import type * as dcaCache from "../dcaCache.js";
import type * as debugCS from "../debugCS.js";
import type * as deleteWeek3 from "../deleteWeek3.js";
import type * as discord from "../discord.js";
import type * as discord_adminSync from "../discord/adminSync.js";
import type * as discord_archiveNoTierRole from "../discord/archiveNoTierRole.js";
import type * as discord_eventSync from "../discord/eventSync.js";
import type * as discord_eventSyncMutations from "../discord/eventSyncMutations.js";
import type * as discord_femaleEvaluatedMembers from "../discord/femaleEvaluatedMembers.js";
import type * as discord_removeAllTierRoles from "../discord/removeAllTierRoles.js";
import type * as discord_roles from "../discord/roles.js";
import type * as discord_sync from "../discord/sync.js";
import type * as discord_tierMismatches from "../discord/tierMismatches.js";
import type * as eventBans_mutations from "../eventBans/mutations.js";
import type * as eventBans_queries from "../eventBans/queries.js";
import type * as eventBans_roleSync from "../eventBans/roleSync.js";
import type * as eventBans_sync from "../eventBans/sync.js";
import type * as eventBans_viewerAuth from "../eventBans/viewerAuth.js";
import type * as events from "../events.js";
import type * as events_debugTeamConsolidation from "../events/debugTeamConsolidation.js";
import type * as events_duoPairs from "../events/duoPairs.js";
import type * as events_duoSelection from "../events/duoSelection.js";
import type * as events_icsImport from "../events/icsImport.js";
import type * as events_management from "../events/management.js";
import type * as events_results from "../events/results.js";
import type * as events_showdown from "../events/showdown.js";
import type * as events_showdownPenalties from "../events/showdownPenalties.js";
import type * as fixImportedDiscordIds from "../fixImportedDiscordIds.js";
import type * as fixImportedWithRoles from "../fixImportedWithRoles.js";
import type * as fixMatchDataSync from "../fixMatchDataSync.js";
import type * as fixMatchPlayerIds from "../fixMatchPlayerIds.js";
import type * as fortnitetracker from "../fortnitetracker.js";
import type * as genderSheet_queries from "../genderSheet/queries.js";
import type * as genderSheet_sync from "../genderSheet/sync.js";
import type * as girlRole_mutations from "../girlRole/mutations.js";
import type * as girlRole_queries from "../girlRole/queries.js";
import type * as girlRole_sync from "../girlRole/sync.js";
import type * as googleSheets from "../googleSheets.js";
import type * as helpers_audit from "../helpers/audit.js";
import type * as helpers_evaluationGender from "../helpers/evaluationGender.js";
import type * as helpers_eventDrivenRebuilds from "../helpers/eventDrivenRebuilds.js";
import type * as helpers_femaleVerification from "../helpers/femaleVerification.js";
import type * as helpers_genderSheetEntries from "../helpers/genderSheetEntries.js";
import type * as helpers_genderSheetSchedule from "../helpers/genderSheetSchedule.js";
import type * as helpers_manualScores from "../helpers/manualScores.js";
import type * as helpers_patchIfChanged from "../helpers/patchIfChanged.js";
import type * as helpers_playerAlt from "../helpers/playerAlt.js";
import type * as helpers_playerDiscordAliases from "../helpers/playerDiscordAliases.js";
import type * as helpers_playerDiscordId from "../helpers/playerDiscordId.js";
import type * as helpers_playerEventStats from "../helpers/playerEventStats.js";
import type * as helpers_playerImportLookup from "../helpers/playerImportLookup.js";
import type * as helpers_playerResults from "../helpers/playerResults.js";
import type * as helpers_publicMemberDirectory from "../helpers/publicMemberDirectory.js";
import type * as helpers_tierSort from "../helpers/tierSort.js";
import type * as http from "../http.js";
import type * as importProcessing from "../importProcessing.js";
import type * as importProcessingActions from "../importProcessingActions.js";
import type * as inGameEarnings_actions from "../inGameEarnings/actions.js";
import type * as inGameEarnings_mutations from "../inGameEarnings/mutations.js";
import type * as inGameEarnings_osirionApi from "../inGameEarnings/osirionApi.js";
import type * as inGameEarnings_queries from "../inGameEarnings/queries.js";
import type * as leaderboardStats from "../leaderboardStats.js";
import type * as lib_eventBanDiscordRoles from "../lib/eventBanDiscordRoles.js";
import type * as lib_eventCache from "../lib/eventCache.js";
import type * as lib_eventLeaderboardLinks from "../lib/eventLeaderboardLinks.js";
import type * as lib_eventLeaderboards_computeEventLeaderboards from "../lib/eventLeaderboards/computeEventLeaderboards.js";
import type * as lib_eventLeaderboards_index from "../lib/eventLeaderboards/index.js";
import type * as lib_eventLeaderboards_sortImports from "../lib/eventLeaderboards/sortImports.js";
import type * as lib_eventLeaderboards_teamGrouping from "../lib/eventLeaderboards/teamGrouping.js";
import type * as lib_eventLeaderboards_types from "../lib/eventLeaderboards/types.js";
import type * as lib_eventSlug from "../lib/eventSlug.js";
import type * as lib_eventTypes from "../lib/eventTypes.js";
import type * as lib_eventWorkflow from "../lib/eventWorkflow.js";
import type * as lib_eventYuniteRequirement from "../lib/eventYuniteRequirement.js";
import type * as lib_importPipeline from "../lib/importPipeline.js";
import type * as lib_importPipelineLogging from "../lib/importPipelineLogging.js";
import type * as lib_importProcessingBatch from "../lib/importProcessingBatch.js";
import type * as lib_importRematch from "../lib/importRematch.js";
import type * as lib_importSource from "../lib/importSource.js";
import type * as lib_memberActivity from "../lib/memberActivity.js";
import type * as lib_playerIdentity from "../lib/playerIdentity.js";
import type * as lib_resolveImportPipelineStep from "../lib/resolveImportPipelineStep.js";
import type * as lib_scrimLeaderboard from "../lib/scrimLeaderboard.js";
import type * as lib_scrimSeriesEventLink from "../lib/scrimSeriesEventLink.js";
import type * as lib_stats_computeContributionScore from "../lib/stats/computeContributionScore.js";
import type * as lib_stats_computeInternalPlayerStats from "../lib/stats/computeInternalPlayerStats.js";
import type * as lib_stats_evaluationStatus from "../lib/stats/evaluationStatus.js";
import type * as lib_stats_filterYuniteResults from "../lib/stats/filterYuniteResults.js";
import type * as lib_stats_gameMode from "../lib/stats/gameMode.js";
import type * as lib_stats_holisticScore from "../lib/stats/holisticScore.js";
import type * as lib_stats_importRecordCache from "../lib/stats/importRecordCache.js";
import type * as lib_stats_listEligiblePlayers from "../lib/stats/listEligiblePlayers.js";
import type * as lib_stats_matchPlayerFromLookup from "../lib/stats/matchPlayerFromLookup.js";
import type * as lib_stats_playerStatsCacheEligibility from "../lib/stats/playerStatsCacheEligibility.js";
import type * as lib_stats_playerStatsCacheStatus from "../lib/stats/playerStatsCacheStatus.js";
import type * as lib_stats_rebuildKind from "../lib/stats/rebuildKind.js";
import type * as lib_stats_syncInternalEventParticipation from "../lib/stats/syncInternalEventParticipation.js";
import type * as lib_stats_thresholds from "../lib/stats/thresholds.js";
import type * as lib_stats_types from "../lib/stats/types.js";
import type * as lib_stats_updatePlayerStatsCache from "../lib/stats/updatePlayerStatsCache.js";
import type * as lib_stats_updateTierEvalForPlayer from "../lib/stats/updateTierEvalForPlayer.js";
import type * as lib_stats_versions from "../lib/stats/versions.js";
import type * as lib_stats_zbdPerformanceStats from "../lib/stats/zbdPerformanceStats.js";
import type * as lib_yunite from "../lib/yunite.js";
import type * as lib_yuniteRateLimit from "../lib/yuniteRateLimit.js";
import type * as memberManagement from "../memberManagement.js";
import type * as migrateHasMatchData from "../migrateHasMatchData.js";
import type * as migrateMembershipStatus from "../migrateMembershipStatus.js";
import type * as migration from "../migration.js";
import type * as migrationDevTools from "../migrationDevTools.js";
import type * as migrations_mergeMinicupIntoScrim from "../migrations/mergeMinicupIntoScrim.js";
import type * as migrations_stripWipSchemaFields from "../migrations/stripWipSchemaFields.js";
import type * as opsHub_access from "../opsHub/access.js";
import type * as opsHub_mutations from "../opsHub/mutations.js";
import type * as opsHub_queries from "../opsHub/queries.js";
import type * as opsHub_responsibilityCatalog from "../opsHub/responsibilityCatalog.js";
import type * as playerAlts from "../playerAlts.js";
import type * as playerEarnings from "../playerEarnings.js";
import type * as playerStats from "../playerStats.js";
import type * as playerStatsCache from "../playerStatsCache.js";
import type * as playerStatsRebuild from "../playerStatsRebuild.js";
import type * as players from "../players.js";
import type * as players_fixPlaceholderIds from "../players/fixPlaceholderIds.js";
import type * as players_importLookup from "../players/importLookup.js";
import type * as players_importMatching from "../players/importMatching.js";
import type * as players_status from "../players/status.js";
import type * as potentialEventCalendar_mutations from "../potentialEventCalendar/mutations.js";
import type * as potentialEventCalendar_queries from "../potentialEventCalendar/queries.js";
import type * as potentialEventCalendar_recurrence from "../potentialEventCalendar/recurrence.js";
import type * as potentialEventCalendar_viewerAuth from "../potentialEventCalendar/viewerAuth.js";
import type * as replays_mutations from "../replays/mutations.js";
import type * as replays_parser from "../replays/parser.js";
import type * as replays_queries from "../replays/queries.js";
import type * as scores from "../scores.js";
import type * as scrimSeries_importFromYunite from "../scrimSeries/importFromYunite.js";
import type * as scrimSeries_mutations from "../scrimSeries/mutations.js";
import type * as scrimSeries_queries from "../scrimSeries/queries.js";
import type * as scrims_mutations from "../scrims/mutations.js";
import type * as scrims_queries from "../scrims/queries.js";
import type * as support from "../support.js";
import type * as sync from "../sync.js";
import type * as thirdParty from "../thirdParty.js";
import type * as thirdPartyMutations from "../thirdPartyMutations.js";
import type * as thirdPartyQueries from "../thirdPartyQueries.js";
import type * as thirdParty_relinkResults from "../thirdParty/relinkResults.js";
import type * as tierHistory from "../tierHistory.js";
import type * as tierReEvaluation from "../tierReEvaluation.js";
import type * as tierReEvaluationBatched from "../tierReEvaluationBatched.js";
import type * as tierSnapshot from "../tierSnapshot.js";
import type * as topFiveCache from "../topFiveCache.js";
import type * as userProvisioning from "../userProvisioning.js";
import type * as users from "../users.js";
import type * as validation_phase3b from "../validation/phase3b.js";
import type * as yunite from "../yunite.js";
import type * as yuniteQueries from "../yuniteQueries.js";
import type * as yunite_checkSurvivalTimeData from "../yunite/checkSurvivalTimeData.js";
import type * as yunite_clear from "../yunite/clear.js";
import type * as yunite_clearHelpers from "../yunite/clearHelpers.js";
import type * as yunite_debug from "../yunite/debug.js";
import type * as yunite_eliminationOverrides from "../yunite/eliminationOverrides.js";
import type * as yunite_fixPlacements from "../yunite/fixPlacements.js";
import type * as yunite_fixPlacementsHelpers from "../yunite/fixPlacementsHelpers.js";
import type * as yunite_lookupEpicRegistration from "../yunite/lookupEpicRegistration.js";
import type * as yunite_lookupPlatform from "../yunite/lookupPlatform.js";
import type * as yunite_matchData from "../yunite/matchData.js";
import type * as yunite_matchDataHelpers from "../yunite/matchDataHelpers.js";
import type * as yunite_platformMutations from "../yunite/platformMutations.js";
import type * as yunite_platforms from "../yunite/platforms.js";
import type * as yunite_populateTeamMembers from "../yunite/populateTeamMembers.js";
import type * as yunite_populateTeamMembersHelpers from "../yunite/populateTeamMembersHelpers.js";
import type * as yunite_recalculateStats from "../yunite/recalculateStats.js";
import type * as yunite_registrationApi from "../yunite/registrationApi.js";
import type * as yunite_sync from "../yunite/sync.js";

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";

declare const fullApi: ApiFromModules<{
  aggregateStats: typeof aggregateStats;
  audienceInsights: typeof audienceInsights;
  audit: typeof audit;
  auth_discord: typeof auth_discord;
  auth_helpers: typeof auth_helpers;
  backfillMatchStats: typeof backfillMatchStats;
  bandwidthBackfill: typeof bandwidthBackfill;
  cacheStatus: typeof cacheStatus;
  calculateContributionScore: typeof calculateContributionScore;
  cleanup: typeof cleanup;
  cleanupDuplicates: typeof cleanupDuplicates;
  clearDeprecatedPlayerRankingFields: typeof clearDeprecatedPlayerRankingFields;
  clearDeprecatedTierEvalPrFields: typeof clearDeprecatedTierEvalPrFields;
  crons: typeof crons;
  dataBackup: typeof dataBackup;
  dcaCache: typeof dcaCache;
  debugCS: typeof debugCS;
  deleteWeek3: typeof deleteWeek3;
  discord: typeof discord;
  "discord/adminSync": typeof discord_adminSync;
  "discord/archiveNoTierRole": typeof discord_archiveNoTierRole;
  "discord/eventSync": typeof discord_eventSync;
  "discord/eventSyncMutations": typeof discord_eventSyncMutations;
  "discord/femaleEvaluatedMembers": typeof discord_femaleEvaluatedMembers;
  "discord/removeAllTierRoles": typeof discord_removeAllTierRoles;
  "discord/roles": typeof discord_roles;
  "discord/sync": typeof discord_sync;
  "discord/tierMismatches": typeof discord_tierMismatches;
  "eventBans/mutations": typeof eventBans_mutations;
  "eventBans/queries": typeof eventBans_queries;
  "eventBans/roleSync": typeof eventBans_roleSync;
  "eventBans/sync": typeof eventBans_sync;
  "eventBans/viewerAuth": typeof eventBans_viewerAuth;
  events: typeof events;
  "events/debugTeamConsolidation": typeof events_debugTeamConsolidation;
  "events/duoPairs": typeof events_duoPairs;
  "events/duoSelection": typeof events_duoSelection;
  "events/icsImport": typeof events_icsImport;
  "events/management": typeof events_management;
  "events/results": typeof events_results;
  "events/showdown": typeof events_showdown;
  "events/showdownPenalties": typeof events_showdownPenalties;
  fixImportedDiscordIds: typeof fixImportedDiscordIds;
  fixImportedWithRoles: typeof fixImportedWithRoles;
  fixMatchDataSync: typeof fixMatchDataSync;
  fixMatchPlayerIds: typeof fixMatchPlayerIds;
  fortnitetracker: typeof fortnitetracker;
  "genderSheet/queries": typeof genderSheet_queries;
  "genderSheet/sync": typeof genderSheet_sync;
  "girlRole/mutations": typeof girlRole_mutations;
  "girlRole/queries": typeof girlRole_queries;
  "girlRole/sync": typeof girlRole_sync;
  googleSheets: typeof googleSheets;
  "helpers/audit": typeof helpers_audit;
  "helpers/evaluationGender": typeof helpers_evaluationGender;
  "helpers/eventDrivenRebuilds": typeof helpers_eventDrivenRebuilds;
  "helpers/femaleVerification": typeof helpers_femaleVerification;
  "helpers/genderSheetEntries": typeof helpers_genderSheetEntries;
  "helpers/genderSheetSchedule": typeof helpers_genderSheetSchedule;
  "helpers/manualScores": typeof helpers_manualScores;
  "helpers/patchIfChanged": typeof helpers_patchIfChanged;
  "helpers/playerAlt": typeof helpers_playerAlt;
  "helpers/playerDiscordAliases": typeof helpers_playerDiscordAliases;
  "helpers/playerDiscordId": typeof helpers_playerDiscordId;
  "helpers/playerEventStats": typeof helpers_playerEventStats;
  "helpers/playerImportLookup": typeof helpers_playerImportLookup;
  "helpers/playerResults": typeof helpers_playerResults;
  "helpers/publicMemberDirectory": typeof helpers_publicMemberDirectory;
  "helpers/tierSort": typeof helpers_tierSort;
  http: typeof http;
  importProcessing: typeof importProcessing;
  importProcessingActions: typeof importProcessingActions;
  "inGameEarnings/actions": typeof inGameEarnings_actions;
  "inGameEarnings/mutations": typeof inGameEarnings_mutations;
  "inGameEarnings/osirionApi": typeof inGameEarnings_osirionApi;
  "inGameEarnings/queries": typeof inGameEarnings_queries;
  leaderboardStats: typeof leaderboardStats;
  "lib/eventBanDiscordRoles": typeof lib_eventBanDiscordRoles;
  "lib/eventCache": typeof lib_eventCache;
  "lib/eventLeaderboardLinks": typeof lib_eventLeaderboardLinks;
  "lib/eventLeaderboards/computeEventLeaderboards": typeof lib_eventLeaderboards_computeEventLeaderboards;
  "lib/eventLeaderboards/index": typeof lib_eventLeaderboards_index;
  "lib/eventLeaderboards/sortImports": typeof lib_eventLeaderboards_sortImports;
  "lib/eventLeaderboards/teamGrouping": typeof lib_eventLeaderboards_teamGrouping;
  "lib/eventLeaderboards/types": typeof lib_eventLeaderboards_types;
  "lib/eventSlug": typeof lib_eventSlug;
  "lib/eventTypes": typeof lib_eventTypes;
  "lib/eventWorkflow": typeof lib_eventWorkflow;
  "lib/eventYuniteRequirement": typeof lib_eventYuniteRequirement;
  "lib/importPipeline": typeof lib_importPipeline;
  "lib/importPipelineLogging": typeof lib_importPipelineLogging;
  "lib/importProcessingBatch": typeof lib_importProcessingBatch;
  "lib/importRematch": typeof lib_importRematch;
  "lib/importSource": typeof lib_importSource;
  "lib/memberActivity": typeof lib_memberActivity;
  "lib/playerIdentity": typeof lib_playerIdentity;
  "lib/resolveImportPipelineStep": typeof lib_resolveImportPipelineStep;
  "lib/scrimLeaderboard": typeof lib_scrimLeaderboard;
  "lib/scrimSeriesEventLink": typeof lib_scrimSeriesEventLink;
  "lib/stats/computeContributionScore": typeof lib_stats_computeContributionScore;
  "lib/stats/computeInternalPlayerStats": typeof lib_stats_computeInternalPlayerStats;
  "lib/stats/evaluationStatus": typeof lib_stats_evaluationStatus;
  "lib/stats/filterYuniteResults": typeof lib_stats_filterYuniteResults;
  "lib/stats/gameMode": typeof lib_stats_gameMode;
  "lib/stats/holisticScore": typeof lib_stats_holisticScore;
  "lib/stats/importRecordCache": typeof lib_stats_importRecordCache;
  "lib/stats/listEligiblePlayers": typeof lib_stats_listEligiblePlayers;
  "lib/stats/matchPlayerFromLookup": typeof lib_stats_matchPlayerFromLookup;
  "lib/stats/playerStatsCacheEligibility": typeof lib_stats_playerStatsCacheEligibility;
  "lib/stats/playerStatsCacheStatus": typeof lib_stats_playerStatsCacheStatus;
  "lib/stats/rebuildKind": typeof lib_stats_rebuildKind;
  "lib/stats/syncInternalEventParticipation": typeof lib_stats_syncInternalEventParticipation;
  "lib/stats/thresholds": typeof lib_stats_thresholds;
  "lib/stats/types": typeof lib_stats_types;
  "lib/stats/updatePlayerStatsCache": typeof lib_stats_updatePlayerStatsCache;
  "lib/stats/updateTierEvalForPlayer": typeof lib_stats_updateTierEvalForPlayer;
  "lib/stats/versions": typeof lib_stats_versions;
  "lib/stats/zbdPerformanceStats": typeof lib_stats_zbdPerformanceStats;
  "lib/yunite": typeof lib_yunite;
  "lib/yuniteRateLimit": typeof lib_yuniteRateLimit;
  memberManagement: typeof memberManagement;
  migrateHasMatchData: typeof migrateHasMatchData;
  migrateMembershipStatus: typeof migrateMembershipStatus;
  migration: typeof migration;
  migrationDevTools: typeof migrationDevTools;
  "migrations/mergeMinicupIntoScrim": typeof migrations_mergeMinicupIntoScrim;
  "migrations/stripWipSchemaFields": typeof migrations_stripWipSchemaFields;
  "opsHub/access": typeof opsHub_access;
  "opsHub/mutations": typeof opsHub_mutations;
  "opsHub/queries": typeof opsHub_queries;
  "opsHub/responsibilityCatalog": typeof opsHub_responsibilityCatalog;
  playerAlts: typeof playerAlts;
  playerEarnings: typeof playerEarnings;
  playerStats: typeof playerStats;
  playerStatsCache: typeof playerStatsCache;
  playerStatsRebuild: typeof playerStatsRebuild;
  players: typeof players;
  "players/fixPlaceholderIds": typeof players_fixPlaceholderIds;
  "players/importLookup": typeof players_importLookup;
  "players/importMatching": typeof players_importMatching;
  "players/status": typeof players_status;
  "potentialEventCalendar/mutations": typeof potentialEventCalendar_mutations;
  "potentialEventCalendar/queries": typeof potentialEventCalendar_queries;
  "potentialEventCalendar/recurrence": typeof potentialEventCalendar_recurrence;
  "potentialEventCalendar/viewerAuth": typeof potentialEventCalendar_viewerAuth;
  "replays/mutations": typeof replays_mutations;
  "replays/parser": typeof replays_parser;
  "replays/queries": typeof replays_queries;
  scores: typeof scores;
  "scrimSeries/importFromYunite": typeof scrimSeries_importFromYunite;
  "scrimSeries/mutations": typeof scrimSeries_mutations;
  "scrimSeries/queries": typeof scrimSeries_queries;
  "scrims/mutations": typeof scrims_mutations;
  "scrims/queries": typeof scrims_queries;
  support: typeof support;
  sync: typeof sync;
  thirdParty: typeof thirdParty;
  thirdPartyMutations: typeof thirdPartyMutations;
  thirdPartyQueries: typeof thirdPartyQueries;
  "thirdParty/relinkResults": typeof thirdParty_relinkResults;
  tierHistory: typeof tierHistory;
  tierReEvaluation: typeof tierReEvaluation;
  tierReEvaluationBatched: typeof tierReEvaluationBatched;
  tierSnapshot: typeof tierSnapshot;
  topFiveCache: typeof topFiveCache;
  userProvisioning: typeof userProvisioning;
  users: typeof users;
  "validation/phase3b": typeof validation_phase3b;
  yunite: typeof yunite;
  yuniteQueries: typeof yuniteQueries;
  "yunite/checkSurvivalTimeData": typeof yunite_checkSurvivalTimeData;
  "yunite/clear": typeof yunite_clear;
  "yunite/clearHelpers": typeof yunite_clearHelpers;
  "yunite/debug": typeof yunite_debug;
  "yunite/eliminationOverrides": typeof yunite_eliminationOverrides;
  "yunite/fixPlacements": typeof yunite_fixPlacements;
  "yunite/fixPlacementsHelpers": typeof yunite_fixPlacementsHelpers;
  "yunite/lookupEpicRegistration": typeof yunite_lookupEpicRegistration;
  "yunite/lookupPlatform": typeof yunite_lookupPlatform;
  "yunite/matchData": typeof yunite_matchData;
  "yunite/matchDataHelpers": typeof yunite_matchDataHelpers;
  "yunite/platformMutations": typeof yunite_platformMutations;
  "yunite/platforms": typeof yunite_platforms;
  "yunite/populateTeamMembers": typeof yunite_populateTeamMembers;
  "yunite/populateTeamMembersHelpers": typeof yunite_populateTeamMembersHelpers;
  "yunite/recalculateStats": typeof yunite_recalculateStats;
  "yunite/registrationApi": typeof yunite_registrationApi;
  "yunite/sync": typeof yunite_sync;
}>;

/**
 * A utility for referencing Convex functions in your app's public API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;

/**
 * A utility for referencing Convex functions in your app's internal API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = internal.myModule.myFunction;
 * ```
 */
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;

export declare const components: {};
